spring:
  kafka:
    bootstrap-servers: 10.129.42.122:9092
    consumer:
      group-id: example-group1
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 500
      session-timeout: 10000
      heartbeat-interval: 3000
      request-timeout: 30000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

  data:
    redis:
      host: localhost
      port: 6379
      password: your_password
      database: 0
      timeout: 2000

  elasticsearch:
    uris: http://127.0.0.1:9200
    connection-timeout: 5s
    socket-timeout: 10s
